version: 2
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/openjdk:11.0.2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Load Dependencies and Build
          command: ./gradlew build

  test:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  version: 2
  integrate:
    jobs:
      - build
      - test:
          requires:
            - build
