version: 2
defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/openjdk:11.0.2

aliases:
  - &restore_cache
    restore_cache:
      keys:
      - v1-dependencies-{{ checksum "build.gradle" }}

  - &save_cache
    save_cache:
      paths:
      - ~/.gradle
      key: v1-dependencies-{{ checksum "build.gradle" }}

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Load Dependencies and Build
          command: ./gradlew build
      - *save_cache

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run Unit Tests
          command: ./gradlew test

workflows:
  version: 2
  integrate:
    jobs:
      - build
      - test:
          requires:
            - build
